export type Stage = {
  id: string;
  title: string;
  code: string;
  short: string;
  when: string;
  goal: string;
  items: string[];
  resources: string[];
  doneWhen: string;
};

export type Level = Stage & { level: number };
export type Track = Stage & { from: string };

export const LEVELS: Level[] = [
  {
    id: "l0",
    code: "L0",
    short: "Foundations",
    level: 0,
    title: "Foundations",
    when: "0-6 months",
    goal: "Write working code and understand how computers and the web work.",
    items: [
      "Learn one language well (Python, Go, Java, C#, or TypeScript)",
      "Data structures: arrays, hash maps, trees, graphs, heaps, queues",
      "Algorithms: sorting, searching, recursion, Big-O",
      "Git, branching, pull requests",
      "Command line and Linux basics",
      "How the web works: HTTP, DNS, TCP/IP, TLS, REST",
      "Basic SQL and one relational database",
    ],
    resources: [
      "CS50 (Harvard, free)",
      "The Missing Semester of Your CS Education (MIT, free)",
      "Grokking Algorithms by Aditya Bhargava",
      "roadmap.sh (for picking a path)",
    ],
    doneWhen: "You can build and deploy a small CRUD app on your own.",
  },
  {
    id: "l1",
    code: "L1",
    short: "Solid Engineer",
    level: 1,
    title: "Solid Engineer",
    when: "6 months - 2 years",
    goal: "Write clean, tested, maintainable code in a team.",
    items: [
      "Clean code: naming, functions, small modules",
      "Unit, integration, and end-to-end testing; TDD basics",
      "Debugging and profiling",
      "Code review (give and receive)",
      "Relational DB design: normalization, indexes, transactions, query plans",
      "One NoSQL store (Redis, MongoDB, or DynamoDB)",
      "API design: REST, pagination, versioning, error handling",
      "CI/CD basics, Docker",
      "Authentication and authorization basics (OAuth2, JWT, sessions)",
    ],
    resources: [
      "The Pragmatic Programmer by Hunt & Thomas",
      "Clean Code by Robert C. Martin (read critically)",
      "Refactoring by Martin Fowler",
      "Use the Index, Luke (use-the-index-luke.com)",
      "Docker's official 'Get Started' docs",
    ],
    doneWhen: "Colleagues trust your PRs and you can own a small feature end to end.",
  },
  {
    id: "l2",
    code: "L2",
    short: "Design Mastery",
    level: 2,
    title: "Senior Engineer, Design Mastery",
    when: "2-5 years",
    goal: "Design modules and services, not just implement tickets.",
    items: [
      "SOLID principles, and when to bend them",
      "GoF design patterns (the 10-12 common ones)",
      "Coupling and cohesion, modularity, separation of concerns",
      "Layered, hexagonal (ports and adapters), and clean architecture",
      "Domain modeling basics (entities, value objects, aggregates)",
      "Concurrency: threads, async, locks, race conditions",
      "Caching strategies and invalidation",
      "Observability: logging, metrics, tracing",
      "Refactoring legacy code safely",
      "Mentor a junior developer",
    ],
    resources: [
      "A Philosophy of Software Design by John Ousterhout",
      "Head First Design Patterns, or Design Patterns by the Gang of Four",
      "Clean Architecture by Robert C. Martin",
      "Patterns of Enterprise Application Architecture by Martin Fowler",
      "refactoring.guru (free pattern catalog)",
    ],
    doneWhen: "You can explain why you chose a design and what you traded away.",
  },
  {
    id: "l3",
    code: "L3",
    short: "Distributed Systems",
    level: 3,
    title: "Systems and Distributed Architecture",
    when: "4-7 years",
    goal: "Design systems that scale, survive failure, and evolve.",
    items: [
      "Monolith vs modular monolith vs microservices (and when each wins)",
      "Event-driven architecture and message queues (Kafka, RabbitMQ, SQS)",
      "CQRS and event sourcing",
      "CAP theorem, consistency models, eventual consistency",
      "Replication, sharding, partitioning",
      "Distributed transactions: sagas, outbox pattern, idempotency",
      "Load balancing, API gateways, service discovery",
      "Resilience: retries, circuit breakers, bulkheads, backpressure",
      "Domain-Driven Design: bounded contexts, context mapping",
      "Do 15+ system design exercises (URL shortener, chat, feed, rate limiter)",
    ],
    resources: [
      "Designing Data-Intensive Applications by Martin Kleppmann",
      "Building Microservices by Sam Newman",
      "Learning Domain-Driven Design by Vlad Khononov (or Evans / Vernon)",
      "Release It! by Michael Nygard",
      "microservices.io patterns catalog",
      "System Design Primer (GitHub, donnemartin)",
      "MIT 6.5840 Distributed Systems (free lectures)",
      "System Design Interview vols. 1-2 by Alex Xu",
    ],
    doneWhen: "You can whiteboard a scalable system and defend its failure modes.",
  },
  {
    id: "l4",
    code: "L4",
    short: "Cloud & Quality",
    level: 4,
    title: "Cloud, Infrastructure, and Quality Attributes",
    when: "5-8 years",
    goal: "Treat performance, security, cost, and operability as design inputs.",
    items: [
      "One cloud deeply (AWS, Azure, or GCP), then compare the others",
      "Infrastructure as code (Terraform or Pulumi)",
      "Kubernetes fundamentals and containers in production",
      "Networking: VPCs, subnets, CDN, ingress",
      "Security architecture: threat modeling, zero trust, secrets, OWASP Top 10",
      "Quality attributes: performance, scalability, availability, security, modifiability, cost",
      "SLIs, SLOs, error budgets",
      "Disaster recovery, RTO/RPO, multi-region",
      "Cost modeling and FinOps basics",
      "Data architecture: warehouses, lakes, streaming pipelines",
      "One cloud architect certification (optional)",
    ],
    resources: [
      "AWS Well-Architected Framework (principles apply to any cloud)",
      "Azure and Google Cloud Architecture Centers",
      "Site Reliability Engineering (sre.google/books)",
      "Accelerate by Forsgren, Humble & Kim",
      "Threat Modeling by Adam Shostack",
      "Building Evolutionary Architectures by Ford, Parsons & Kua",
    ],
    doneWhen: "You can justify an architecture against explicit quality targets and a budget.",
  },
  {
    id: "l5",
    code: "L5",
    short: "The Architect Role",
    level: 5,
    title: "The Architect Role",
    when: "6-10 years",
    goal: "Be effective as an architect: mostly communication and judgment.",
    items: [
      "Write at least 10 real Architecture Decision Records (ADRs)",
      "C4 model diagrams (context, container, component)",
      "Trade-off analysis of architecture styles (ATAM-style thinking)",
      "Practice 3-5 architecture katas under time pressure",
      "Turn vague business needs into explicit constraints",
      "Explain the same design to engineers, managers, and executives",
      "Measure, communicate, and prioritize technical debt",
      "Build vs buy and vendor evaluation",
      "Governance without bottlenecks (fitness functions, guardrails)",
      "Lead a migration (monolith decomposition or cloud move)",
      "Write and present design docs / RFCs",
    ],
    resources: [
      "Fundamentals of Software Architecture by Richards & Ford",
      "Software Architecture: The Hard Parts by Ford et al.",
      "The Software Architect Elevator by Gregor Hohpe",
      "Software Architecture in Practice by Bass, Clements & Kazman",
      "c4model.com, arc42.org, adr.github.io",
      "Team Topologies by Skelton & Pais",
      "The Staff Engineer's Path by Tanya Reilly",
    ],
    doneWhen: "Teams seek your design reviews and your decisions hold up a year later.",
  },
  {
    id: "l6",
    code: "L6",
    short: "Strategic Architect",
    level: 6,
    title: "Hero, Enterprise and Strategic Architect",
    when: "9+ years",
    goal: "Shape technology direction across an organization.",
    items: [
      "Enterprise architecture frameworks (TOGAF, Zachman) and when they actually help",
      "Align technology strategy with business strategy",
      "Platform engineering and internal developer platforms",
      "Organizational design and Conway's Law",
      "Multi-year technology roadmaps and portfolio governance",
      "M&A and legacy modernization strategy",
      "Regulatory and compliance architecture (GDPR, SOC 2, PCI)",
      "Govern AI-assisted development (review, security, licensing, cost)",
      "Evaluate emerging tech (AI/ML systems, edge) without chasing hype",
      "Build an architecture community of practice",
      "Speak, write, or teach publicly",
    ],
    resources: [
      "Good Strategy / Bad Strategy by Richard Rumelt",
      "An Elegant Puzzle by Will Larson",
      "The Phoenix Project by Gene Kim",
      "Designing Machine Learning Systems by Chip Huyen",
      "TOGAF documentation (The Open Group)",
      "InfoQ and QCon talks",
    ],
    doneWhen: "Leaders ask you which bets to make, and the 3-year strategy you wrote still holds.",
  },
];

export const TRACKS: Track[] = [
  {
    id: "t1",
    code: "T1",
    short: "API Styles",
    from: "l1",
    title: "API Styles and Integration",
    when: "from Level 1",
    goal: "Pick the right interface style, not just REST by default.",
    items: [
      "OpenAPI and contract-first design",
      "gRPC and Protocol Buffers",
      "GraphQL: schema design, N+1, federation",
      "WebSockets and server-sent events",
      "Async APIs and event contracts (AsyncAPI, schema registry)",
      "Versioning, deprecation, and backward compatibility",
    ],
    resources: [
      "roadmap.sh API Design roadmap",
      "grpc.io and graphql.org docs",
      "asyncapi.com",
      "Microsoft REST API Guidelines (GitHub)",
    ],
    doneWhen: "You can justify REST vs gRPC vs GraphQL vs events for a given consumer.",
  },
  {
    id: "t2",
    code: "T2",
    short: "Frontend & Mobile",
    from: "l2",
    title: "Frontend and Mobile Architecture",
    when: "from Level 2",
    goal: "Architect the client side, not only the backend.",
    items: [
      "Rendering strategies: CSR, SSR, SSG, islands",
      "State management and data fetching patterns",
      "Micro-frontends: when they help and when they hurt",
      "Design systems and component libraries",
      "Performance budgets and Core Web Vitals",
      "Mobile architecture (MVVM, offline-first, sync)",
    ],
    resources: [
      "patterns.dev",
      "web.dev",
      "micro-frontends.org",
      "Official iOS and Android architecture guides",
    ],
    doneWhen: "You can decide how a product's UI is split, rendered, and deployed.",
  },
  {
    id: "t3",
    code: "T3",
    short: "Testing & Reliability",
    from: "l3",
    title: "Testing and Reliability Engineering",
    when: "from Level 3",
    goal: "Prove the architecture works under real conditions.",
    items: [
      "Contract testing (Pact) between services",
      "Load and stress testing (k6, Gatling)",
      "Chaos engineering and game days",
      "Architecture fitness functions in CI",
      "Testing in production: canaries, feature flags",
      "Incident response and blameless postmortems",
    ],
    resources: [
      "docs.pact.io",
      "k6.io docs",
      "principlesofchaos.org",
      "Building Evolutionary Architectures",
    ],
    doneWhen: "Failure modes are tested before customers find them.",
  },
  {
    id: "t4",
    code: "T4",
    short: "Data, ML & AI",
    from: "l4",
    title: "Data, ML and AI Systems",
    when: "from Level 4",
    goal: "Architect data platforms and AI-powered features.",
    items: [
      "Polyglot persistence: choose stores by access pattern",
      "Stream processing (Kafka Streams, Flink)",
      "Lakehouse, warehouse, data mesh concepts",
      "Data quality, lineage, and governance",
      "ML pipelines, feature stores, model serving, drift",
      "LLM and RAG architecture: retrieval, evals, guardrails, cost and latency",
    ],
    resources: [
      "Fundamentals of Data Engineering by Reis & Housley",
      "Designing Machine Learning Systems by Chip Huyen",
      "Data Mesh by Zhamak Dehghani",
      "Designing Data-Intensive Applications",
    ],
    doneWhen: "You can design a data or AI feature end to end, including how it is monitored.",
  },
  {
    id: "t5",
    code: "T5",
    short: "Leadership",
    from: "l2",
    title: "Leadership and Soft Skills",
    when: "all levels",
    goal: "Influence decisions without owning the org chart.",
    items: [
      "Influence without authority",
      "Negotiation and resolving conflicts between teams",
      "Run an effective design review",
      "Write clear, short technical documents",
      "Present trade-offs to executives and non-technical stakeholders",
      "Coach engineers and grow other architects",
    ],
    resources: [
      "Crucial Conversations by Patterson et al.",
      "Never Split the Difference by Chris Voss",
      "The Software Architect Elevator",
      "Staff Engineer by Will Larson (staffeng.com)",
    ],
    doneWhen: "Disagreements end in a documented decision everyone can live with.",
  },
  {
    id: "t6",
    code: "T6",
    short: "Domain Specializations",
    from: "l3",
    title: "Domain Specializations",
    when: "optional",
    goal: "Learn the constraints specific to your industry.",
    items: [
      "Fintech: ledgers, idempotency, reconciliation, PCI DSS",
      "Healthcare: HIPAA, HL7 / FHIR interoperability",
      "E-commerce: inventory, checkout, search, peak load",
      "IoT and embedded: constrained devices, OTA updates, edge",
      "Games: server-authoritative state, netcode, matchmaking",
      "Public sector and regulated systems: audit, sovereignty",
    ],
    resources: [
      "hl7.org/fhir",
      "Game Programming Patterns by Robert Nystrom",
      "Designing Data-Intensive Applications (ledger and consistency chapters)",
      "Regulator and standards documents for your domain",
    ],
    doneWhen: "You can name the three constraints that make your domain different.",
  },
  {
    id: "t7",
    code: "T7",
    short: "Career & Interviews",
    from: "l5",
    title: "Career and Interviews",
    when: "Levels 4-6",
    goal: "Turn skills into the role.",
    items: [
      "Build a portfolio of design docs and ADRs (sanitized)",
      "Practice architecture and system design interviews",
      "Get a stretch assignment: lead one cross-team design",
      "Find a sponsor or mentor who is already an architect",
      "Decide your path: solution, enterprise, or staff-plus engineer",
      "Keep a decision journal and review it yearly",
    ],
    resources: [
      "staffeng.com",
      "ByteByteGo",
      "Neal Ford's architecture katas",
      "The Software Architect Elevator",
    ],
    doneWhen: "You have shipped at least one cross-team design with your name on it.",
  },
];

export const STAGES: Stage[] = [...LEVELS, ...TRACKS];

export const findStage = (id: string) => STAGES.find((s) => s.id === id);

export const parentLevel = (t: Track) => LEVELS.find((l) => l.id === t.from)!;

export const COURSE_LINKED: Record<string, "go" | "ds"> = {
  "l0.0": "go",
  "l0.1": "ds",
};
